services:
  - type: web
    name: mini-cms
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python create_superuser.py
    startCommand: gunicorn cms_project.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" 
      - key: WAGTAILADMIN_BASE_URL
        sync: false
